<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="DeltaXAssignment" duration-ms="141417" started-at="2018-07-12T15:09:20Z" finished-at="2018-07-12T15:11:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="141417" started-at="2018-07-12T15:09:20Z" finished-at="2018-07-12T15:11:41Z">
      <class name="com.tests.DriverClass">
        <test-method status="PASS" signature="testInit(java.lang.String)[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="testInit" is-config="true" duration-ms="4950" started-at="2018-07-12T15:09:20Z" finished-at="2018-07-12T15:09:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInit -->
        <test-method status="PASS" signature="NaivateToUrl()[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="NaivateToUrl" is-config="true" duration-ms="1117" started-at="2018-07-12T15:09:25Z" finished-at="2018-07-12T15:09:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NaivateToUrl -->
        <test-method status="PASS" signature="NegativeScenarios()[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="NegativeScenarios" duration-ms="131275" started-at="2018-07-12T15:09:26Z" finished-at="2018-07-12T15:11:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NegativeScenarios -->
        <test-method status="PASS" signature="NaivateToUrl()[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="NaivateToUrl" is-config="true" duration-ms="193" started-at="2018-07-12T15:11:38Z" finished-at="2018-07-12T15:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NaivateToUrl -->
        <test-method status="PASS" signature="PositiveScenario(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="PositiveScenario" duration-ms="3172" started-at="2018-07-12T15:11:38Z" data-provider="iterator" finished-at="2018-07-12T15:11:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sasidhar]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[reddy]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Engineering]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Vsasidharreddy]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Sa12345dhar]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[Sa12345dhar]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[sasidharreddy98@gmail.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[7034604852]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PositiveScenario -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.tests.DriverClass@a38d7a3]" name="tearDown" is-config="true" duration-ms="1" started-at="2018-07-12T15:11:41Z" finished-at="2018-07-12T15:11:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
This value is not valid error message displayed for confirm passowrd expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for phone expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
This value is not valid error message displayed for confirm passowrd expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for Email expected [true] but found [false],
This value is not valid error message displayed for phone expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.tests.DriverClass.tearDown(DriverClass.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.DriverClass -->
    </test> <!-- Test -->
  </suite> <!-- DeltaXAssignment -->
</testng-results>
